package cat.freya.khs.db

import java.sql.Connection
import java.sql.PreparedStatement
import java.sql.ResultSet
import javax.sql.DataSource

// wrappers for java sql objects to allow compatability
// with older jdbc drivers

// even though we load our own version of the jdbc driver,
// server software may force their own version upon us, so
// we must be ready to support that :/

class KhsDataSource(val inner: DataSource) : DataSource by inner {
    override fun getConnection(): Connection = KhsConnection(inner.connection)
}

class KhsConnection(val inner: Connection) : Connection by inner {
    override fun isValid(timeout: Int): Boolean =
        runCatching { inner.isValid(timeout) }.getOrElse { !inner.isClosed }

    override fun prepareStatement(sql: String?): PreparedStatement =
        KhsPreparedStatement(inner.prepareStatement(sql))

    override fun prepareStatement(sql: String?, autoGeneratedKeys: Int): PreparedStatement =
        KhsPreparedStatement(inner.prepareStatement(sql, autoGeneratedKeys))

    override fun prepareStatement(sql: String?, columnIndexes: IntArray?): PreparedStatement =
        KhsPreparedStatement(inner.prepareStatement(sql, columnIndexes))

    override fun prepareStatement(
        sql: String?,
        columnNames: Array<out String>?,
    ): PreparedStatement = KhsPreparedStatement(inner.prepareStatement(sql, columnNames))
}

class KhsPreparedStatement(val inner: PreparedStatement) : PreparedStatement by inner {
    override fun isClosed(): Boolean = runCatching { inner.isClosed }.getOrElse { false }

    override fun getResultSet(): ResultSet? =
        runCatching { inner.resultSet }
            .getOrElse {
                // we need to return null instead of throwing, as
                // that is the correct modern jdbc behavior

                val msg = it.message ?: ""
                if (!msg.contains("no ResultSet available")) throw it

                return null
            }
}
