name: "Feature request"
description: "You would like a new feature added to the plugin"
title: "feature: FEATURE REQUEST NAME"
labels: ["feature"]
body:
  - type: "checkboxes"
    id: "checklist"
    attributes:
      label: "Acknowledgements"
      description: "Mark all that apply"
      options:
        - label: This is not a duplicate feature request
        - label: This feature is not already in the plugin
        - label: I checked the latest version of the plugin
        - label: I am willing to submit a PR to implement this feature
    validations:
      required: true
  - type: "textarea"
    id: "description"
    attributes:
      label: "Describe the feature"
      description: "Concisely describe what you would like added"
    validations:
      required: true
